apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-mfjg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-mfjg
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-mfjg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-mfjg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-mfjg
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-yuxo-tenant/dotnet-component/devfile-sample-dotnet60-basic-mfjg@sha256:6f2b492011d53f1cebc77a3580bd8dffbfd3e3027386184af97c3b24760c4f82
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
